// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://durwmxstshmxfmspmhow.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR1cndteHN0c2hteGZtc3BtaG93Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzU4MjcxMjYsImV4cCI6MjA1MTQwMzEyNn0.jpjTSKoBm3FZovdMSEQ1cia5nLiWnn3TyFF5k2cDvCw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);